<?php
declare(strict_types=1);

// Tillo SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

TilloUtility::setRegistrar(function (TilloUtility $u): void {
    $u->clean = [TilloClean::class, 'call'];
    $u->done = [TilloDone::class, 'call'];
    $u->make_error = [TilloMakeError::class, 'call'];
    $u->feature_add = [TilloFeatureAdd::class, 'call'];
    $u->feature_hook = [TilloFeatureHook::class, 'call'];
    $u->feature_init = [TilloFeatureInit::class, 'call'];
    $u->fetcher = [TilloFetcher::class, 'call'];
    $u->make_fetch_def = [TilloMakeFetchDef::class, 'call'];
    $u->make_context = [TilloMakeContext::class, 'call'];
    $u->make_options = [TilloMakeOptions::class, 'call'];
    $u->make_request = [TilloMakeRequest::class, 'call'];
    $u->make_response = [TilloMakeResponse::class, 'call'];
    $u->make_result = [TilloMakeResult::class, 'call'];
    $u->make_point = [TilloMakePoint::class, 'call'];
    $u->make_spec = [TilloMakeSpec::class, 'call'];
    $u->make_url = [TilloMakeUrl::class, 'call'];
    $u->param = [TilloParam::class, 'call'];
    $u->prepare_auth = [TilloPrepareAuth::class, 'call'];
    $u->prepare_body = [TilloPrepareBody::class, 'call'];
    $u->prepare_headers = [TilloPrepareHeaders::class, 'call'];
    $u->prepare_method = [TilloPrepareMethod::class, 'call'];
    $u->prepare_params = [TilloPrepareParams::class, 'call'];
    $u->prepare_path = [TilloPreparePath::class, 'call'];
    $u->prepare_query = [TilloPrepareQuery::class, 'call'];
    $u->graphql_body = [TilloGraphql::class, 'body'];
    $u->graphql_errors = [TilloGraphql::class, 'errors'];
    $u->result_basic = [TilloResultBasic::class, 'call'];
    $u->result_body = [TilloResultBody::class, 'call'];
    $u->result_headers = [TilloResultHeaders::class, 'call'];
    $u->transform_request = [TilloTransformRequest::class, 'call'];
    $u->transform_response = [TilloTransformResponse::class, 'call'];
});
